### ISSUE TITLE
Dynamic cluster

### ISSUE THREAD

**Issue by yatli** [microsoft/GraphEngine#108]
Currently, GE adopts a fixed cluster configuration scheme. That is, during cluster initialization, a server instance read from the config file once, obtain a list of peer servers, and then connect to them -- there's no chance for another server to join the already-running cluster. This makes it difficult for tasks like auto-scale, high-availability, elastic container management etc.

To work around this, we should implement dynamic cluster management. Upon successful authentication, any server can be attached/detached from the cluster. A gossip-like protocol is required for this scheme to function properly, and first of all, I think we'd better seek to integrate such capabilities from other ecosystems, to focus on examining the design ideas instead of a particular implementation.

Next, the programming model of GE requires a fixed number of "partitions" (think of graph partitions), which, upon dynamic cluster membership changes, could be inconsistent with the actual machines. Thus, we should introduce an abstract layer, to make a graph partition logical instead of physical. The number of logical partitions shall be fixed as we do now for physical machines, because for many graph workloads, this lead to more stable and predictable performance. A physical machine could act the role of multiple logical partitions, and one logical partition can be further scattered to multiple physical machines (one DHT for each partition, etc.), where the partitioning table and the address space table shall be synchronized across the cluster, with a persistent key-value store, such as the one provided by Azure Service Fabric, ZooKeeper, etcd, etc.

When multiple servers take on the same logical partition role, they effectively form an availability group, as our current configuration stubs suggest.

Then we should consider the message passing problem. All the `serverId` parameters and alike, are subject to changes due to this additional layer. They should be refactored into `availabilityGroupId` instead. Furthermore, the behavior of a message passing protocol is determined by the actual semantic of the message. Here I'll list a few that we adopted during the development of our various ad-hoc high-availability solutions:

- `FirstAvailable`: typically used for read-only scenarios, for example, graph traversal queries in LIKQ. This scheme stably pick the first available server instance from the AG and send the message over. The choice of physical machine is consistent given that there's no change to the cluster membership.
- `Consistent`: Requires the message to be successfully sent to all the instances in an AG. Useful for write protocols.
- `Vote`: Send the message to all the instances in an AG, and expect a certain fraction of consistent returns.
- `EventualConsistent`: do not wait for confirmation on all the instances, but guarantees that the message will be eventually delivered, and the result consistent.
- `Fixed`: Typically used for a stateful transaction protocol, where local context is kept on a physical server for performance considerations, and thus all the messages further sent to this AG should be routed back to where the local context resides. Note that multiple transactions should be able to pick different instances from an AG.
- `RoundRobin`: As the name implies, mainly for computation-intensive, read-only load balancing.

There could be more message passing patterns, and we are open to all kinds of suggestions on this topic.

Next, data persistence. Given that the data of a partition may now be scattered across the cluster, it does not make sense to keep the fixed partition data image scheme. Instead, a distributed file system with native high-availability is more favorable. Again we should consider the implementations from other ecosystems, for example HDFS. Then the data could be incrementally dumped to the storage, one segment after another. Data migration and in-memory redundancy are actually highly related topics, as we can think of the process as making data persistent by transfer the data to other instances.

With these pieces pulled together, we should be having a fully working dynamic cluster programming model, which is compatible with most service hosting models. And it would be more "native" when we deploy GE into such environments.

**Comment by TaviTruman** [comment]
@yatli This is some strong and timely thinking in this critical design space; this is one of the important differences and incongruences between the native GE programming models (Cluster configuration) and the Azure Service Fabric. As the SF is automatically scaling horizontally and offers Reliability, Federation, Hosting and Communication, Management subsystems seamless integration with SF is the logic way to proceed. 

Early on @shaobin (Bin) gave me the idea of using a wrapper-type idiom to mesh with the SF Communications and Transport subsystems and a simple "Hello World" GE App that interfaces with a WCF Client calling into a Azure SF Microservices method that calls a GE Method to retrieve a "Greetings Response" from the Memory Cloud. This "hot-mess" worked but it hardly the method to use; this only works in the simplest of configuring and processing modes limiting (**_Stateless, non-replicating_**) the SF and GE configuration to a "Fixed" non-clustering model - hardly what we need or want. To merge the best of both worlds (GE and SF) we will mostly likely need to adapt and extend the GE Cluster model and embrace the notion of "Dynamic Cluster" - very exciting and very cool! 

Right now I am working on integrating GE with SF at the Transport and Communications subsystem layers; the intent here is to be a "first-class" Communications Listener so that there is no need for a communications wrapping thing. Once we have that done then we will need the idea of creating an efficient "Service Cluster" abstraction of the GE Clustering model and key to this all working is the SF Hosting model. I really like the concepts you have for ad-hoc high availability solutions and I think there is room for some extended semantics given the capabilities of the SF Partitioning and Replica capabilities.

I think a  good-goal, relative to SF, is to create as seamless and as first-class an integration and workflow matching scenario is possible within the SF ecosystem and that we work well with both "Stateful and Stateless" programming models. So, in addition to changes/adaptations/extensions to GE in the way of "Dynamic Cluster" support, we will also need to adapt the GE app model into supporting the "Actor" pattern for "fire-n-forget" stateless/reliable computing or "Stateful" and "Reliable" computing useful in writing "Semantic Reasoners" and Gaming Engines.

Key and central to any App model in SF and ZooKeeper is the "Message Passing Protocol" and how to persist data stored in the GE MemoryCloud in a dynamic clustered computing environment; again, it looks like the GE team has already been thinking about this and we have a way forward in Azure SF with the "Reliable Service" and "Reliable Actor" APIs and how these capabilities interplay with SF support for Partitions and Replicas.

I think we will also need some extensions to the GE TSL model in support of the following:

- Methods marked as "Reliable" and "Stateful"
- Modules that represent an "Actor" implementation with the parametric specification of "Actor Lifetime and Actor States" for Reliable Actors
- Cells that are available for Replication [Required or Optional]
- Cells "State" and "Replica" Roles ["Primary", "Active Secondary", and "Idle Secondary"]
- Cells that represent an "Event", "Timers" and "Reminders" for GE Actor implementations
- Methods that represent "Provider" stubs

There's more to talk and ponder about, I think we have enough in front of us to keep us busy for a little while.

**Comment by yatli** [comment]
Done, the rest of the work, integration tests, etc., should be done in #120
