### ISSUE TITLE
Question: Is it possible to change the schema without re-importing all the data?

### ISSUE THREAD

**Issue by bingzhangdai** [microsoft/GraphEngine#126]
As time passes by, we may find our previous designed schema out of date. We may need sometimes add more fields to the cell. And possibly, but rarely, delete some fields. 

I added a new field (type `string`) to one of the cells defined in `.tsl` file. Then recompiled the source code and called `Global.CloudStorage.LoadStorage()` to load the previous saved storage. However, I got an error

> [ INFO    ] Loading cell type signatures.
> [ ERROR   ] Inconsistent cell type signature for type #0.
> [ ERROR   ] Expecting: {List<{string|List<{long|int|int}>|string}>}.
> [ ERROR   ] Got: {List<{string|List<{long|int|int}>}>}.

And I failed to add value to the newly added field. 

Is it possible to change the schema a little bit without reloading all the data? Or how to design the schema so that it is scalable and can thus avoid this problem.

**Comment by bingzhangdai** [comment]
As far as I tested, we could only append the definition of new cell to the `.tsl` file. (A waning will be prompted, but programmers will always ignore the warning, 233). Inserting the definition above other existing cells will also result in error. 

Besides, we cannot change the existing cells' fields/schema even the order. Any changes will result in error. If you do want to change the schema, reimporting is needed. I think this significantly limits the usage scenarios. :(

Is there some other methods to alleviate the issue?

**Comment by yatli** [comment]
There's an option in LoadStorage to ignore the schema mismatch, but you have to be very careful to access the mismatched cell type.

For example if you have {List<{string|List<{long|int|int}>|string}>} and later would like to change to {List<{string|List<{long|int|int}>}>}, the new accessor will not take into account of the last string in a list, with the direct consequence that the length of the string will be interpreted as the length of the next string (surprise!).

Our typical approach to this problem is to create a new type {List<{string|List<{long|int|int}>}>}.
This will allow you to incrementally migrate the entities of the old type to the new one. A high-level ICell adapter can do the mapping for you, so that the change can be transparent to the upper layer of your application. 64K types should keep this going sustainable, just make sure to eventually migrate all the data so the type system is not exhausted.

**Comment by yatli** [comment]
btw great question! I'd definitely put this into a tutorial!

**Comment by bingzhangdai** [comment]
Thanks very much for your reply! This is a feasible approach. After all, we do not change the schema very often.

You mentioned "high-level ICell adapter". Is there some reference to it?

**Comment by yatli** [comment]
@bingzhangdai there you go: https://github.com/Microsoft/GraphEngine/blob/master/samples/freebase-likq/freebase-likq/FreebaseAdapter.cs

**Comment by yatli** [comment]
@bingzhangdai please check out the `availability` branch, we've got schema evolution working and you'll have immutable types and composite extensions now!

**Comment by bingzhangdai** [comment]
@yatli Great! I have seen lots of changes 👍. It is a little bit hard to read the source code diff directly. Once the docs are updated, I will try new features immediately and step into the lib to see how it works. Thanks!

btw, could you provide some brief instructions about how to read the source code? Maybe the code structure. It would definitely help me better understand the mechanism. If your are too busy, I can do it myself :)

**Comment by yatli** [comment]
@bingzhangdai it depends on which part do you want to get started with first:
Trinity.C is the memory management and native networking routines.
Trinity.Core is the upper part for a better user experience (yeah I know this is vague...)
 - TSL type system
 - Various extension points
 - Configuration
 - CommunicationInstance, modules, etc.
 - message passing endpoints
Trinity.TSL is codegen for generating cell types, data accessor and rpc stubs

**Comment by yatli** [comment]
closing the issue now. will have an example on storage schema evolution.

**Comment by bingzhangdai** [comment]
@yatli Seems that there will be lots of new features 👍 Looking forward.
