### ISSUE TITLE
Trinity.FFI build-py

### ISSUE THREAD

**Issue by PhilPJL** [microsoft/GraphEngine#171]
I'm unable to get this to work.  The script says that the Python build environment isn't installed.
Using Visual Studio 2017 15.6.2 with all Python options installed.

![capture](https://user-images.githubusercontent.com/271656/37559395-3a71e1c8-2a1d-11e8-98e0-eb167537a980.PNG)

Any tips on what I need to install to get this working?

**Comment by yatli** [comment]
Hey @PhilPJL you discovered the new Python FFI! :)
This project is still at very early stage so there's literally zero documentation for building at the moment unfortunately.. I'll try list the procedure here:

1. Install the pythonnet wheel, we placed a nightly build binary in the FFI folder. We currently need pythonnet to do dotnet hosting from python side but this could change, we could make our own hosting mechanism.
2. Install SWIG -- it's an awesome interop codegen and according to our benchmarking, with very good performance. If you have a package manager like `chocolatey` installed, you can simply install that with `choco install -y swig`
3. Just in case the VS project complains about missing pythonnet projects, do a `git submodule update --recursive` so that you clone the pythonnet repo.

Let me know if this works for you or not. There could be other little tasks to be done :)
Good luck and have fun!

**Comment by PhilPJL** [comment]
@yatli 
I may pass on this step for now.  I can get the VSExtension built by removing the dependency on FFI.Python.

There is limited (but clearly not enough) documentation in the 'Building for Windows' section at https://github.com/Microsoft/GraphEngine.
