### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by PhilPJL** [microsoft/GraphEngine#173]
- Both the freebase-likq and friends samples need 'allow unsafe code' checked in the project properties.

- Why does VS show errors for generated code for some GraphEngine projects and not others?  e.g.

![image](https://user-images.githubusercontent.com/271656/37567428-b9080e76-2abe-11e8-89f5-607e946cd7a6.png)

I did have 'full solution analysis' turned on.  I thought it may have been an issue with that but turning it off made no difference.

- I assume that the freebase-likeq sample should contain
`            FanoutSearchModule.EnableExternalQuery(true);
`
as per the LIKQ test service.

- Also spelling error here 'queray':
![image](https://user-images.githubusercontent.com/271656/37567907-b556a556-2ac5-11e8-9772-8aa7c3be6c24.png)

**Comment by yatli** [comment]
@PhilPJL if the nuget package is properly installed, you usually don't need to explicitly specify "allow unsafe" because it's already done in GE build targets. So this is most likely a package reference issue -- the build targets are not found. This problem will then lead to TSL file not codegen'ed into C# files, and therefore the server base, the accessor, methods to be overridden, are not found.

Also, sometimes closing and opening the project again will help VS to refresh the cache. It may take some time till it realizes that "oh these things are there, not errors"

**Comment by yatli** [comment]
fixed, closing
