### ISSUE TITLE
Trinity.TSL.CodeTemplates.csproj build error when $(ProjectDir) path contains whitespaces

### ISSUE THREAD

**Issue by rucub100** [microsoft/GraphEngine#192]
In **GraphEngine/src/Trinity.TSL/Trinity.TSL.CodeTemplates/Trinity.TSL.CodeTemplates.csproj**:

```xml
⋮
  <Target Name="AfterBuild">
    <Exec Command="$(OutputPath)Trinity.TSL.Metagen.exe $(ProjectDir)" />
  </Target>
</Project>
```

My temp fix for that problem is 
```xml
<Exec Command="$(OutputPath)Trinity.TSL.Metagen.exe &quot;$(ProjectDir)\&quot; />
```

However, I have also observed that the tsl script is not compiled correctly

![path_with_whitespace](https://user-images.githubusercontent.com/27758942/39262719-7e38e660-48c0-11e8-8570-36e99f7959f8.PNG)

 for paths with white spaces.
E.g. the SSSP sample cannot create API code from templates properly. But when I move the whole dir to a path without white space (such as C:\samples\SSSP) the sample works fine (after cleanup and remove all obj and bin stuff)

![just_copied_to_other_path_no_white_space](https://user-images.githubusercontent.com/27758942/39262718-7e1a0a9c-48c0-11e8-9883-a830d8e7278d.PNG)

**My Env-Specs:**
- Windows 10 64bit
- Visual Studio 2017 **with** Windows 10 SDK (10.0.15063.0) for Desktop C++, .NET Core SDK 2.0,  Visual Studio 2015 C++ toolchain **as per README**

**Comment by yatli** [comment]
hi @rucub100!

thanks for reporting the problem! that's kind of 'uh oh' because I've been working on the spaces quite often.. I'll fix this one and update `master`.
however, I'm pretty sure that `Trinity.TSL.MetaGen.exe` is only used to build `Trinity.TSL.CodeGen.exe`, not for user tsl templates; Could you please try again with a project in spaced path? Sometimes unloading the user proj from VS and reloading it will help -- a VS problem. :)
