### ISSUE TITLE
Unable to Build DataImporter

### ISSUE THREAD

**Issue by TaviTruman** [microsoft/GraphEngine#194]
I just fetched the latest source and I am getting build errors. I did the following to try to fix:

- Ran Clean on GraphEngine.DataImporter

- Changed Framework mode to .net461

- Changed Processor Configuration to x64

- Executed build.ps1 in the tools directory via PowerShell

- Attempted to build GraphEngine.DataImporter project but still getting the compilation error captured in the image below

![image](https://user-images.githubusercontent.com/5692812/39392312-604b4aea-4a68-11e8-96c5-f577014a4b0a.png)

**Comment by yatli** [comment]
@TaviTruman I think it's a rename issue. Could you please try rename all CellID to CellId?

**Comment by TaviTruman** [comment]
@yatli Yes- renaming did the trick but a singular error still exist. 
This code does not compile:
 **if (cellid == null) cellid = Global.LocalStorage.NewRandomCellID();**

I can't see via intellisense what method should be used instead of NewRandomCellID.

**Comment by yatli** [comment]
again, NewRandomCellID->NewRandomCellId.

**Comment by TaviTruman** [comment]
@yatli Yeah that is what I thought as well but NewRandomCellId does not come-up in intellisense autocomplete and I tried to use NewRandomCellId but still got an error; let me try to unload and reload the project.

**Comment by yatli** [comment]
uh oh, let me know if it doesn't work for you. I'll take a look into the code

**Comment by TaviTruman** [comment]
@yatli no - there is not such NewRandomCellId method on Global.LocalStorage  - still getting cannot resolve symbol.

![image](https://user-images.githubusercontent.com/5692812/39398835-bded61f0-4ac8-11e8-82a6-d9dc669ad7fa.png)

**Comment by nvankaam** [comment]
@TaviTruman I think the NewRandomCellId() is removed from LocalMemoryStorage and is replaced by NewCellId() on the "CellIdFactory"

Commit: https://github.com/Microsoft/GraphEngine/commit/19e0e9f018d3b7df01926ab1cc302f1696d9f445

**Comment by yatli** [comment]
thanks @nvankaam for helping out!
I'd like to update a little bit on this area -- we don't encourage users to use the existing CellIdFactory implementation because it is not collision-free nor distributed-aware. I've been attempting multiple times to bring up something else to provide better guarantees, and get even other benefits like distributed indices (yes they're highly related!). My bandwidth is currently spread across other aspects but once I've got free slots this feature is definitely high on my list.

**Comment by yatli** [comment]
that being said, we may have inconsistency issues with GraphEngine.DataImporter because it relies solely on CellIdFactory and hash functions to generate cell ids.

**Comment by yatli** [comment]
related: https://github.com/Microsoft/GraphEngine/issues/118

**Comment by TaviTruman** [comment]
Yikes 😓 we have a large volume of rdf triples to load; I will see if the fix works after some testing. It looks like newcellid just generates a random number and will not be good enough. So @yati should I even continue to try to use dataimporter given it's current state?

**Comment by yatli** [comment]
@TaviTruman if you really look into the code or investigate the samples, you'll see that you can already specify a key hasher with TSL attributes.
Generating random ids definitely will not work out for your scenario, because you'll at least have to relate the cell id to a unique identifier (a guid or something).

We've successfully imported FreeBase (billions of triples) with DataImporter with literally zero collision.
Please take a look at the sample TSL.

**Comment by TaviTruman** [comment]
@yati thanks for the feedback Yatao; yes, I see that one is able to adjust the code so that control of the hashkey value is possible. As we all have lots of things in motion it helps to know what one can expect from the code when it comes to built-in capabilities. I know it's possible load large volumes of triples via the DataImporter as your documentation says so; I assumed that specific capabilities is native. The freebase example made available is post processing of the Dataimporter effect. I'm clear on how to proceed - thanks for the clear and poient advice. I'm closing this issue as I have what I need.
