### ISSUE TITLE
Feature req: Tinkerpop support

### ISSUE THREAD

**Issue by joeyfezster** [microsoft/GraphEngine#6]
Hey guys!
Kudos on releasing this to the OS community :D

I wanted to ask if you're planning on implementing apache's tinkerpop in ms graph engine.
this feature would be crucial for most neo4j, titan (r.i.p), and all the other graphdb's users to port their systems to ms graph engine.

**Comment by yatli** [comment]
Hi @joyfezster!

Thanks for your comments!
We had some discussions about integration with other runtimes (JVM etc.) before, it wasn't really viable because GE depended on some sophisticated interop techniques that brings uncertainty to... well, another layer of interop.

But now, as we are moving to CoreCLR, we not only have a more straightforward interop model, but also gain cross-platform capabilities. What's a better time to discuss this with you guys? :)

So I would like to ask if there is any particular workload on your mind. What role do you expect GE to play in this integration? I mean, there could be a lot of different approaches, from a RESTful surface to a full model that precisely let Tinkerpop know about its capabilities (Strongly-typed? Edge modeling? Persistency? Dynamic schema? Distributed? Transactions? Thread model? In-place computation? etc. etc.)

Also, it would be great if someone could give a try to stick the two sides together, as we move along the xplat development.

**Comment by amalic** [comment]
I would also be interrested in Tinkerpop support. Especially in a RDF-Sail!

@yati: --> http://tinkerpop.apache.org/

**Comment by yatli** [comment]
Closing this one at the moment.
