### ISSUE TITLE
Do we have any deployment examples for multiple multiple machines?

### ISSUE THREAD

**Issue by twocode** [microsoft/GraphEngine#62]
AKA. Non embedded mode?

**Comment by yatli** [comment]
@twocode, we are working to bring online more distributed mode docs and examples.

**Comment by rajkumarvishnu** [comment]
Yes, this would be absolutely. Thanks!

**Comment by sebdau** [comment]
This was added to the current milestone.
Any plans / rough estimations when this might be available?
Thanks, Seb

**Comment by yatli** [comment]
@sebdau the doc for the new config system is added, you could follow the instructions there to get a cluster up and running.
In the mean time we will be working on automatic deployment (packing your app into docker then send them into a swarm, DC/OS, etc.), no hard timeline, but it's likely that we can get something in the next three months. Please stay tuned. :)

**Comment by sebdau** [comment]
Thanks, can you share a link to the doc page - did not find it?

Container packaging is nice but unless it comes with the ability to deploy a highly available distributed service (aka GraphEngine PaaS), it wont help us further.

**Comment by yatli** [comment]
@sebdau HA mode and service fabric support is almost there. I'm closing this issue now -- after a lot of trials I think the current way of doing HA in service fabric is much cleaner -- see: https://github.com/Microsoft/GraphEngine/tree/master/src/Modules/GraphEngine.ServiceFabric/Trinity.ServiceFabric.GraphEngineService

Not so different from other SF stateful services, and not so different from a local deployment either. :)

**Comment by sebdau** [comment]
Thanks for the update @yatli !

What exactly does almost there mean?
 - will there be a final sample project for GE in SF?
 - can I already try it out or are there known issues?

**Comment by yatli** [comment]
hi @sebdau!

The design and core implementation are done. I'm doing a series of tutorials and docs, together with some useful utility packages.
Also, we have kicked off an internal bug bash on the GE-SF integration, so while the interfaces are solid now, the implementation may have some issues not yet known -- we have to do both more unit testing and integration testing.

As the vsextension is dusted off, I will make some GE-SF templates so that you can build and deploy your GE-SF instance very quickly. But before that, you can take a look at the solution folder of the GE-SF integration shown above, build the thing and deploy -- it works for both local and real SF cluster, and azure blob storage as the persistent storage backend.

**Comment by sebdau** [comment]
Sounds wonderful, please keep me in the loop :-)

**Comment by yatli** [comment]
sure, will keep you updated!
